name: Playit RDP Tunnel on Ubuntu

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Install XFCE and XRDP
      run: |
        sudo apt update
        sudo apt install -y xfce4 xfce4-goodies xrdp
        sudo systemctl enable xrdp
        sudo systemctl start xrdp

    - name: Configure XRDP for XFCE
      run: |
        echo "xfce4-session" > ~/.xsession

    - name: Set password for runner user
      run: echo "runner:p@ssw0rd!" | sudo chpasswd

    - name: Download Playit.gg agent
      run: |
        curl -L https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-linux-x86_64 -o playit
        chmod +x playit

    - name: Start Playit.gg agent
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PL }}
      run: |
        ./playit --secret $PLAYIT_AUTH_KEY &

    - name: Keep the workflow running
      run: sleep 11800
